spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/krainet
    username: anton
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: localhost
    port: 1027
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


